Repository AY2425S2-CS2113-F11-1/tp, pull requests merged in 2025-03, with the labels that each got.

#2 Add personal particulars to project
  docs/AboutUs.md
Labels: tutorial practice

#4 Added Seung Yoon
  docs/AboutUs.md
  docs/sy/Seung Yoon Lee CV 4.pdf
  docs/sy/beans.avif
  docs/sy/img.png
Labels: tutorial practice

#6 Updated AboutUs.md - Added my details
  docs/AboutUs.md
Labels: tutorial practice

#7 Amirhusaini06 update about us
  docs/AboutUs.md
Labels: tutorial practice

#8 Edit AboutUs.md
  docs/AboutUs.md
  docs/pics/joshua.JPG
  docs/pics/sy.png
  docs/sy/Seung Yoon Lee CV 4.pdf
  docs/sy/beans.avif
  docs/team/LEESY02.md
  docs/team/amirhusaini06.md
  docs/team/b1inmeister.md
  docs/team/himethcodes.md
Labels: type.Enhancement

#9 Edit AboutUs.md
  docs/AboutUs.md
  docs/pics/amir.jpg
  docs/pics/himeth.jpg
Labels: type.Enhancement

#5 rozaliesmit AboutUs
  README.md
  docs/AboutUs.md
Labels: type.Task, tutorial practice
